---

openvpn_enabled: yes                                # The role is enabled
openvpn_version: "2.4"

openvpn_etcdir: /etc/openvpn
openvpn_keydir: "{{openvpn_etcdir}}/keys"

openvpn_use_pam_plugin: /usr/lib/openvpn/plugins/openvpn-plugin-auth-pam.so


openvpn_management_port: 80

# Installation settings
openvpn_use_external_repo: true                 # Enable upstream OpenVPN repository
openvpn_use_system_easyrsa: true                   # Install EasyRSA from system packages

# Default settings (See OpenVPN documentation)
openvpn_host: "{{ router_external_ip }}"              # The server address
openvpn_port: 1194
openvpn_proto: udp
openvpn_dev: tun
openvpn_server: 10.8.0.0 255.255.255.0              # Set empty for skip
openvpn_bridge: {}
openvpn_max_clients: 10
openvpn_log: /var/log/openvpn.log                   # Log's directory
openvpn_keepalive: "10 120"
openvpn_ifconfig_pool_persist: ipp.txt
openvpn_comp_lzo: yes                               # Enable compression
openvpn_cipher: AES-128-CBC                              # Encryption algorithm
openvpn_status: openvpn-status.log
openvpn_verb: 3
openvpn_tls_auth : True                            # Enable perfect forward secracyxy
openvpn_tls_key  : "ta.key"
openvpn_user: nobody
openvpn_group: nogroup
openvpn_resolv_retry: infinite
openvpn_client_to_client: yes
openvpn_server_options:
  - push "route 10.180.37.128 255.255.255.192"
  #- management {{ router_fqdn }} {{ openvpn_management_port }}  # Additional server options
                                                                # openvpn_server_options:
                                                    # - dev-node MyTap
                                                    # - client-to-client
openvpn_client_options:                             # Additional client options
  - auth SHA256                                     # openvpn_client_options:
                                                    # - dev-node MyTap
                                                    # - client-to-client

openvpn_key_country: "NO"
openvpn_key_province: "OSL"
openvpn_key_city: "Oslo"
openvpn_key_org: "DSB"
openvpn_key_email: "ken.tallakstad@dsb.no"
openvpn_key_ou: "IT"
openvpn_key_size: 2048

openvpn_clients: [client]                         # Make clients certificate
openvpn_clients_revoke: []                        # Revoke clients certificates

# Use PAM authentication
openvpn_use_pam: yes
openvpn_use_pam_users: []                         # If empty use system users
                                                  # otherwise use users from the option
                                                  # openvpn_use_pam_users:
                                                  # - { name: user, password: password }

# LDAP authentication and configuration (optional)
openvpn_use_ldap: no
openvpn_ldap_tlsenable: 'no'
openvpn_ldap_follow_referrals: 'no'

# Use simple authentication (default is disabled)
openvpn_simple_auth: no
openvpn_simple_auth_password: ""

# Whether to embed CA, cert, and key info inside client OVPN config file.
openvpn_unified_client_profiles: yes
openvpn_client_config_dir: /etc/openvpn/clients
