- hosts:
    #ubuntu_router
    ubuntu_router_lan
  become: yes

  roles:
  - ../roles/openvpn
  #- ../../ansible-ubuntu-router/roles/ubuntuAddLoginUser

  vars:
    openvpn_use_pam: yes
    openvpn_clients: "{{ ibm_open_vpn_users }}"
    openvpn_use_pam_users: "{{ ibm_open_vpn_pam_users }}"

  vars_prompt:
    - name: "box_user"
      prompt: "Enter Sherpa Box user"
      private: no

    - name: "box_pass"
      prompt: "Enter Sherpa Box pass"
      private: yes
