- hosts:
    #ubuntu_router
    ubuntu_router_lan
  become: yes

  roles:
  - ../roles/openvpn

  vars:
    openvpn_use_pam: yes
    openvpn_clients: "{{ ibm_open_vpn_users }}"
    openvpn_use_pam_users: "{{ ibm_open_vpn_pam_users }}"
    box_user: "user"
    box_pass: "pass"

